// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCz9gUcACXFQkMx811zl173KRzcR-dA7jw',
    appId: '1:164130590556:web:076b0a896185e04cbffb99',
    messagingSenderId: '164130590556',
    projectId: 'elbi-food-sharing-4ca40',
    authDomain: 'elbi-food-sharing-4ca40.firebaseapp.com',
    storageBucket: 'elbi-food-sharing-4ca40.firebasestorage.app',
    measurementId: 'G-H09GQ19JJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd4x65E-GyeU5B6j-bNrwysgsEZO3ccIs',
    appId: '1:164130590556:android:76607744519ffd76bffb99',
    messagingSenderId: '164130590556',
    projectId: 'elbi-food-sharing-4ca40',
    storageBucket: 'elbi-food-sharing-4ca40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf4epa2-Kov_vHQNWfR1DFy_ytQ01-YJQ',
    appId: '1:164130590556:ios:b10078b032126c6bbffb99',
    messagingSenderId: '164130590556',
    projectId: 'elbi-food-sharing-4ca40',
    storageBucket: 'elbi-food-sharing-4ca40.firebasestorage.app',
    iosBundleId: 'com.example.projectCmsc23',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf4epa2-Kov_vHQNWfR1DFy_ytQ01-YJQ',
    appId: '1:164130590556:ios:b10078b032126c6bbffb99',
    messagingSenderId: '164130590556',
    projectId: 'elbi-food-sharing-4ca40',
    storageBucket: 'elbi-food-sharing-4ca40.firebasestorage.app',
    iosBundleId: 'com.example.projectCmsc23',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCz9gUcACXFQkMx811zl173KRzcR-dA7jw',
    appId: '1:164130590556:web:fe43164ec2c8ac26bffb99',
    messagingSenderId: '164130590556',
    projectId: 'elbi-food-sharing-4ca40',
    authDomain: 'elbi-food-sharing-4ca40.firebaseapp.com',
    storageBucket: 'elbi-food-sharing-4ca40.firebasestorage.app',
    measurementId: 'G-6374LFP0BH',
  );
}
